"""Layering guard: the dbt graph must respect staging -> intermediate ->
core -> marts (PROJECT_PLAN Revision v1.2).

Reads dbt/target/manifest.json, which is regenerated by `make dbt-dag`
or any dbt build/parse — it can be stale relative to uncommitted model
edits until one of those runs; regenerate before trusting a green run.
"""

import json
from pathlib import Path

import pytest

from running_pipeline import dbt_dag

MANIFEST_PATH = Path(__file__).resolve().parent.parent / "dbt" / "target" / "manifest.json"

# Allowed parent groups per model layer. Deliberately MINIMAL: it encodes
# exactly the sanctioned v1.2 graph, including the documented exception
# that intermediate and core read raw_strava.streams directly (stream
# payloads are deliberately unstaged). core <- seeds and core <- staging
# are omitted because nothing uses them; widening this matrix is a
# deliberate, reviewed one-line change.
ALLOWED_PARENTS = {
    "staging": frozenset({"sources"}),
    "intermediate": frozenset({"sources", "staging", "intermediate"}),
    "core": frozenset({"sources", "intermediate"}),
    "marts": frozenset({"core", "seeds", "marts"}),
}


@pytest.fixture(scope="module")
def graph():
    if not MANIFEST_PATH.is_file():
        pytest.skip("dbt manifest not generated — run `make dbt-dag`")
    nodes, edges = dbt_dag.build_graph(json.loads(MANIFEST_PATH.read_text()))
    return {node.unique_id: node for node in nodes}, edges


def test_every_model_belongs_to_a_known_layer(graph):
    nodes, _ = graph
    strays = {
        n.unique_id: n.group
        for n in nodes.values()
        if n.resource_type == "model" and n.group not in ALLOWED_PARENTS
    }
    assert strays == {}, f"models outside the four layer folders: {strays}"


def test_model_dependencies_respect_the_layer_matrix(graph):
    nodes, edges = graph
    violations = [
        f"{nodes[parent].group}.{nodes[parent].label} -> {nodes[child].group}.{nodes[child].label}"
        for parent, child in edges
        if nodes[child].resource_type == "model"
        and nodes[parent].group not in ALLOWED_PARENTS.get(nodes[child].group, frozenset())
    ]
    assert violations == [], "layering violations:\n" + "\n".join(violations)
