"""Layering guard: the dbt graph must respect staging -> intermediate ->
core -> marts (PROJECT_PLAN Revision v1.2 and its follow-up).

Reads dbt/target/manifest.json, which is regenerated by `make dbt-dag`
or any dbt build/parse — it can be stale relative to uncommitted model
edits until one of those runs; regenerate before trusting a green run.
"""

import json
from pathlib import Path

import pytest

from running_pipeline import dbt_dag

MANIFEST_PATH = Path(__file__).resolve().parent.parent / "dbt" / "target" / "manifest.json"

# Allowed parent groups per model layer (source parents are handled
# separately below — no group set may grant blanket access to sources).
# Deliberately MINIMAL: it encodes exactly the sanctioned graph;
# widening is a deliberate, reviewed change. core <- seeds, core <-
# staging, and core <- core are omitted because nothing uses them.
# intermediate <- seeds is the Revision v1.4 widening: hr_bands band
# assignment happens at sample grain, which only intermediate sees —
# proven red on that exact edge before this line changed.
ALLOWED_PARENTS = {
    "staging": frozenset(),
    "intermediate": frozenset({"staging", "intermediate", "seeds"}),
    "core": frozenset({"intermediate"}),
    "marts": frozenset({"core", "seeds", "marts"}),
}

# source() is a staging privilege. The single sanctioned exception
# (PROJECT_PLAN Revision v1.2 follow-up): stream payloads are
# deliberately unstaged, readable from INTERMEDIATE models only.
SOURCE_EXCEPTIONS = {
    "intermediate": frozenset({"source.running_analytics.raw_strava.streams"}),
}


def _edge_allowed(parent, child):
    if parent.resource_type == "source":
        if child.group == "staging":
            return True
        return parent.unique_id in SOURCE_EXCEPTIONS.get(child.group, frozenset())
    return parent.group in ALLOWED_PARENTS.get(child.group, frozenset())


@pytest.fixture(scope="module")
def graph():
    if not MANIFEST_PATH.is_file():
        pytest.skip("dbt manifest not generated — run `make dbt-dag`")
    nodes, edges = dbt_dag.build_graph(json.loads(MANIFEST_PATH.read_text()))
    return {node.unique_id: node for node in nodes}, edges


def test_every_model_belongs_to_a_known_layer(graph):
    nodes, _ = graph
    strays = {
        n.unique_id: n.group
        for n in nodes.values()
        if n.resource_type == "model" and n.group not in ALLOWED_PARENTS
    }
    assert strays == {}, f"models outside the four layer folders: {strays}"


def test_model_dependencies_respect_the_layer_matrix(graph):
    nodes, edges = graph
    violations = [
        f"{nodes[parent].group}.{nodes[parent].label} -> {nodes[child].group}.{nodes[child].label}"
        for parent, child in edges
        if nodes[child].resource_type == "model"
        and not _edge_allowed(nodes[parent], nodes[child])
    ]
    assert violations == [], "layering violations:\n" + "\n".join(violations)
